// Seed data for Daily Living Labs Knowledge Portal
window.SEED = {
  documents: [
    // Spring 2026 — Project Overview / Strategy
    { id: "d1", title: "Executive Summary", description: "Top-level overview of the Daily Living Labs Knowledge Portal capstone.",
      phase: "Spring 2026", category: "Project Overview", status: "Approved", needsReview: false,
      version: "1.0", updated: "2026-05-10", owner: "Chelsea", tags: ["overview", "summary"],
      audience: ["Sponsor", "Academic Supervisor"], thumb: "exec", googleDocs: true,
      views: 1248, downloads: 214 },
    { id: "d2", title: "Project Overview", description: "Full project background, scope, and approach.",
      phase: "Spring 2026", category: "Project Overview", status: "Approved", needsReview: false,
      version: "1.2", updated: "2026-05-08", owner: "Chelsea", tags: ["scope"],
      audience: ["Sponsor"], thumb: "project", googleDocs: true,
      views: 892, downloads: 138 },
    { id: "d3", title: "Functional & Technical Requirements", description: "Detailed FR and TR specs for the portal MVP.",
      phase: "Spring 2026", category: "Technical Documentation", status: "In Review", needsReview: true,
      version: "1.3", updated: "2026-05-09", owner: "Chelsea", tags: ["requirements", "MVP"],
      audience: ["Designer", "Developer"], thumb: "specs", googleDocs: true,
      views: 561, downloads: 72 },
    { id: "d4", title: "Style Guide", description: "Brand colors, type, components, accessibility tokens.",
      phase: "Spring 2026", category: "UX & Design", status: "Approved", needsReview: false,
      version: "1.0", updated: "2026-05-07", owner: "Chelsea", tags: ["brand", "design system"],
      audience: ["Designer"], thumb: "style", googleDocs: true,
      views: 410, downloads: 64 },
    { id: "d5", title: "Future State Recommendations", description: "Roadmap of post-MVP recommendations.",
      phase: "Spring 2026", category: "Future Opportunities", status: "Draft", needsReview: false,
      version: "0.8", updated: "2026-05-04", owner: "Chelsea", tags: ["roadmap"],
      audience: ["Sponsor"], thumb: "future", googleDocs: true,
      views: 220, downloads: 31 },
    { id: "d6", title: "User Journey Map v2", description: "Stakeholder-by-phase journey across the portal.",
      phase: "Spring 2026", category: "UX & Design", status: "In Review", needsReview: true,
      version: "2.0", updated: "2026-05-12", owner: "Chelsea", tags: ["research", "journey"],
      audience: ["Designer"], thumb: "journey", googleDocs: false,
      views: 188, downloads: 22 },
    { id: "d7", title: "Stakeholder Interview Summary", description: "Findings from sponsor + advisor interviews.",
      phase: "Spring 2026", category: "Research & Insights", status: "Approved", needsReview: false,
      version: "1.0", updated: "2026-04-28", owner: "Chelsea", tags: ["research"],
      audience: ["Sponsor"], thumb: "interviews", googleDocs: true,
      views: 312, downloads: 45 },
    { id: "d8", title: "Mission Impact Statement", description: "Daily Living Labs mission alignment.",
      phase: "Spring 2026", category: "Strategy & Planning", status: "Approved", needsReview: false,
      version: "1.0", updated: "2026-04-22", owner: "Chelsea", tags: ["mission"],
      audience: ["Sponsor"], thumb: "mission", googleDocs: true,
      views: 280, downloads: 38 },
    { id: "d9", title: "Capstone Pitch Deck", description: "June 1 capstone pitch presentation.",
      phase: "Spring 2026", category: "Presentations", status: "Approved", needsReview: false,
      version: "1.0", updated: "2026-05-30", owner: "Chelsea", tags: ["pitch"],
      audience: ["Academic Supervisor"], thumb: "pitch", googleDocs: false,
      views: 145, downloads: 28 },
    // Fall 2026 placeholders
    { id: "d10", title: "Data Governance Policy", description: "How stakeholder and analytics data is handled.",
      phase: "Fall 2026", category: "Governance & Sign-Offs", status: "Draft", needsReview: true,
      version: "0.4", updated: "2026-05-06", owner: "Chelsea", tags: ["governance"],
      audience: ["Sponsor"], thumb: "governance", googleDocs: true,
      views: 88, downloads: 12 },
    { id: "d11", title: "Technical Architecture (planned)", description: "Detailed architecture, services, and integrations.",
      phase: "Fall 2026", category: "Technical Documentation", status: "Draft", needsReview: false,
      version: "0.1", updated: "2026-05-01", owner: "Chelsea", tags: ["architecture"],
      audience: ["Developer"], thumb: "arch", googleDocs: false,
      views: 42, downloads: 4 },
    { id: "d12", title: "API Requirements (draft)", description: "External and internal API surface for the portal.",
      phase: "Fall 2026", category: "Technical Documentation", status: "In Review", needsReview: true,
      version: "0.3", updated: "2026-05-09", owner: "Chelsea", tags: ["api"],
      audience: ["Developer"], thumb: "api", googleDocs: true,
      views: 60, downloads: 8 },
    // Future Work
    { id: "d13", title: "AI-Powered Document Q&A", description: "Speculative feature spec.",
      phase: "Future Work", category: "Future Opportunities", status: "Draft", needsReview: false,
      version: "0.1", updated: "2026-04-15", owner: "Chelsea", tags: ["AI"],
      audience: ["Developer"], thumb: "ai", googleDocs: false,
      views: 30, downloads: 3 },
    { id: "d14", title: "Role-Based Permissions Plan", description: "Future auth architecture.",
      phase: "Future Work", category: "Strategy & Planning", status: "Draft", needsReview: false,
      version: "0.1", updated: "2026-04-10", owner: "Chelsea", tags: ["auth"],
      audience: ["Developer"], thumb: "rbac", googleDocs: false,
      views: 22, downloads: 1 }
  ],

  bigIdeas: [
    { id: "i1", title: "Adaptive Onboarding Experience", desc: "Personalize Start Here per stakeholder role.", author: "Alex K.", category: "Future Feature", color: "yellow", x: 0, y: 0 },
    { id: "i2", title: "AI-Powered Search Enhancements", desc: "Semantic search across PDF contents.", author: "Jamie L.", category: "Technical Improvement", color: "pink", x: 0, y: 0 },
    { id: "i3", title: "Unified Component Library", desc: "Shared UI kit across DLL products.", author: "Taylor S.", category: "Technical Improvement", color: "mint", x: 0, y: 0 },
    { id: "i4", title: "Data Insights for Daily Living Outcomes", desc: "Tie analytics to lived-experience metrics.", author: "Priya M.", category: "Research Opportunity", color: "blue", x: 0, y: 0 },
    { id: "i5", title: "Accessible Sticky Note Reordering", desc: "Keyboard shortcuts to rearrange notes.", author: "Anonymous", category: "Accessibility Improvement", color: "lavender", x: 0, y: 0 },
    { id: "i6", title: "Sponsor Quarterly Digest", desc: "Auto-summarize portal activity each quarter.", author: "Chelsea", category: "Content Idea", color: "peach", x: 0, y: 0 }
  ],

  activity: [
    { id: "a1", type: "view", title: "Style Guide", who: "you", when: "2h ago" },
    { id: "a2", type: "edit", title: "Functional Requirements v1.3", who: "Jamie Lee", when: "5h ago" },
    { id: "a3", type: "view", title: "Stakeholder Interview Summary", who: "Taylor Smith", when: "Yesterday" },
    { id: "a4", type: "download", title: "Project Overview", who: "you", when: "2d ago" },
    { id: "a5", type: "review", title: "Data Governance Policy flagged", who: "Chelsea", when: "3d ago" }
  ],

  signoffForms: [
    { id: "sf-branding", title: "Branding Sign-Off", subtitle: "Approve brand colors, type system, logo usage, and visual identity guidelines.",
      icon: "palette", owner: "Chelsea", phase: "Spring 2026",
      preparedBy: "Chelsea", preparedFor: "Daily Living Labs Sponsor",
      monthYear: "May 2026", version: "1.0",
      relatedDocIds: ["d4"],
      checklist: [
        { id: "b1", label: "Brand color palette and contrast ratios", relatedDocIds: ["d4"] },
        { id: "b2", label: "Typography system and hierarchy", relatedDocIds: ["d4"] },
        { id: "b3", label: "Logo usage and clear-space rules", relatedDocIds: ["d4"] },
        { id: "b4", label: "Iconography and illustration style", relatedDocIds: ["d4"] },
        { id: "b5", label: "Overall brand identity for the portal", relatedDocIds: ["d4"] }
      ] },
    { id: "sf-social", title: "Social Media Sign-Off", subtitle: "Approve social channels, voice, posting cadence, and visual templates.",
      icon: "share", owner: "Chelsea", phase: "Spring 2026",
      preparedBy: "Chelsea", preparedFor: "Daily Living Labs Sponsor",
      monthYear: "May 2026", version: "0.9",
      relatedDocIds: ["d8"],
      checklist: [
        { id: "s1", label: "Proposed channel strategy", relatedDocIds: ["d8"] },
        { id: "s2", label: "Voice & tone guidelines", relatedDocIds: ["d8"] },
        { id: "s3", label: "Post-template visual system", relatedDocIds: ["d4", "d8"] },
        { id: "s4", label: "Overall social media plan", relatedDocIds: ["d8"] }
      ] },
    { id: "sf-tech", title: "Tech Stack Sign-Off", subtitle: "Approve hosting, frameworks, integrations, and data architecture.",
      icon: "code", owner: "Chelsea", phase: "Fall 2026",
      preparedBy: "Chelsea", preparedFor: "Daily Living Labs Sponsor",
      monthYear: "September 2026", version: "0.4",
      relatedDocIds: ["d11", "d12"],
      checklist: [
        { id: "t1", label: "Front-end framework choice", relatedDocIds: ["d11"] },
        { id: "t2", label: "Hosting and CI/CD plan", relatedDocIds: ["d11"] },
        { id: "t3", label: "Third-party integrations", relatedDocIds: ["d12"] },
        { id: "t4", label: "Data and storage model", relatedDocIds: ["d10", "d11"] },
        { id: "t5", label: "Overall technical stack", relatedDocIds: ["d11", "d12"] }
      ] },
    { id: "sf-fsr", title: "Future State Recommendations", subtitle: "Acknowledge post-MVP recommendations and the prioritized roadmap.",
      icon: "compass", owner: "Chelsea", phase: "Future Work",
      preparedBy: "Chelsea", preparedFor: "Daily Living Labs Sponsor",
      monthYear: "May 2026", version: "0.8",
      relatedDocIds: ["d5"],
      checklist: [
        { id: "f1", label: "Recommended next-phase features", relatedDocIds: ["d5", "d13"] },
        { id: "f2", label: "Items out of scope for MVP", relatedDocIds: ["d5"] },
        { id: "f3", label: "Prioritization rationale", relatedDocIds: ["d5"] },
        { id: "f4", label: "Future-state roadmap as a working plan", relatedDocIds: ["d5", "d14"] }
      ] }
  ],

  timeline: [
    { id: "t1", date: "2026-05-20", title: "Design Review Workshop", phase: "Spring 2026", status: "Upcoming" },
    { id: "t2", date: "2026-06-01", title: "Capstone Pitch", phase: "Spring 2026", status: "Milestone" },
    { id: "t3", date: "2026-06-17", title: "Governance Committee Meeting", phase: "Spring 2026", status: "Upcoming" },
    { id: "t4", date: "2026-07-01", title: "Summer Build Kickoff", phase: "Spring 2026", status: "Upcoming" },
    { id: "t5", date: "2026-08-25", title: "Fall 2026 Phase Begins", phase: "Fall 2026", status: "Milestone" },
    { id: "t6", date: "2026-09-15", title: "Technical Architecture Sign-Off", phase: "Fall 2026", status: "Upcoming" },
    { id: "t7", date: "2026-10-20", title: "Mid-Capstone Review", phase: "Fall 2026", status: "Upcoming" },
    { id: "t8", date: "2026-12-05", title: "Capstone Presentation", phase: "Fall 2026", status: "Milestone" }
  ]
};
